### ISSUE TITLE
Improper use of create_employee() return value.

### ISSUE THREAD

**Issue by zacryol** [skippycrow/T3_CS2450_001#25]
`Database.create_employee()` returns the Employee object that was created.

At https://github.com/skippycrow/T3_CS2450_001/blob/main/project/Add_Employee_Frame.py#L191 , this code is written with the assumption that `create_employee()` would return that same id that was passed in, causing an error right after, when that "id" is passed into `set_employee_data()`

**Comment by skippycrow** [comment]
https://github.com/skippycrow/T3_CS2450_001/tree/Bug_Fix

**Comment by skippycrow** [comment]
Please review @zacryol

**Comment by zacryol** [comment]
or you can save the id you get from `self.add_emp_id_entry.get()` into a var, them pass that into `create_employee()`, rather than get the id from the employee that was just created.
Also, for change review, it's better to submit a pull request, as it's easier to see what specifically was changed.

**Comment by skippycrow** [comment]
Will you work this out? Code is your specialty.

**Comment by zacryol** [comment]
work what out?

**Comment by skippycrow** [comment]
Get the code functional/refine it to meet standards. I'm writing a user manual right now and don't have the time
