### ISSUE TITLE
EmployeeListFrame needs to update to show new Employee

### ISSUE THREAD

**Issue by zacryol** [skippycrow/T3_CS2450_001#42]
after adding an Employee via the AddEmployeeFrame, the EmployeeListFrame does not update to reflect that change.

**Comment by ACast1** [comment]
I should be fixed now, can you try again and let me know if you are still seeing this issue?

**Comment by zacryol** [comment]
If something gets fixed, you can close the issue
Ideally, create a pull request for the change that fixes it, and link it to the issue, rather than just pushing and saying "it probably works now."
