### ISSUE TITLE
Unintuitive navigation regarding EmployeeProfile frame.

### ISSUE THREAD

**Issue by zacryol** [skippycrow/T3_CS2450_001#43]
Both LandingFrame and Employee_List_Frame have the option to travel to EmployeeProfile frame. EmployeeProfile frame has a "Back" button. However, the Back button will always go back to the Landing frame, regardless of which frame it was that led to it.

Either that button should have its text changed to indicate specifically that it goes back to a certain frame, or only allow going to that frame from one other, so there is only one to go back to, or track which frame led to it, and have the back button go back to that one.

**Comment by Jon-nim** [comment]
Also ran into the issue when you edit your own employee profile frame. If you hit cancel you'll go back to employee_list_frame.
to recreate error: login> go to profile > edit employee > cancel

**Comment by ACast1** [comment]
These issues should be fixed now
