### ISSUE TITLE
Employee Profile doesn't pull in all of the extra data for the employee

### ISSUE THREAD

**Issue by skippycrow** [skippycrow/T3_CS2450_001#49]

**Comment by skippycrow** [comment]
May be in the "tyler-profile-update" branch. Please review for a merge

**Comment by skippycrow** [comment]
Rename: Employee Classification -> Pay Type (Salary, Hourly, Commission)

Pay Type value -> converted to text based on value (Salary:1, Hourly:2, Commission:3)
Pay Method value -> converted to text based on value (ACH:1, Mail:2)

hide nonapplicable pay type values (Play around with add/edit to see which you need to see for which type)

Routing/account number should be hidden if method is set to mail

**Comment by TylerJDav** [comment]
Employee "Classification" renamed to "Pay Type"
Pay Type/Method translated to English displays using dictionaries

Salary employees only see salary field; hourly employees only see hourly field; commission employees see salary and commission fields

Routing/Account #s only show when Pay Method set to ACH
