### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by skippycrow** [skippycrow/T3_CS2450_001#51]
Show/hide buttons based on permissions as defined in the requirements specifications

**Comment by skippycrow** [comment]
Employee to employee view 
- when viewing other profiles it shows correct info, However, the back button does take you back to the list, it takes to you back to landing
- Employees shouldn't be able to add other employees/export/run payroll. buttons need to be hidden rather than the popup

**Comment by ACast1** [comment]
Those issues should be fixed now.
