### ISSUE TITLE
When adding an employee, restrict the user to defined data types

### ISSUE THREAD

**Issue by Jon-nim** [skippycrow/T3_CS2450_001#54]
When I added an employee I input all that I thought would be accurate data. ended up with this error when I tried to edit the profile of the emplyee I just made 
![Capture](https://user-images.githubusercontent.com/42918097/144515230-765bd0b7-c1f0-4cbf-8486-4b700326809b.PNG)

**Comment by ACast1** [comment]
Should be fixed now. Try again and if it works you should be good to close this issue

**Comment by zacryol** [comment]
I'm not seeing this bug.
