### ISSUE TITLE
After adding employee data is persistant

### ISSUE THREAD

**Issue by Jon-nim** [skippycrow/T3_CS2450_001#56]
After adding an employee , if you go to add a new employee. The page will pop up with all the information of the previous time you added the employee. 

This was after I added one employee and tried to add another.
![image](https://user-images.githubusercontent.com/42918097/144889608-5891336c-c36a-46e6-acd1-97f0ffb01d11.png)

**Comment by zacryol** [comment]
the `Controller.py` calls `update()` on the new frame when switching (https://github.com/skippycrow/T3_CS2450_001/blob/main/project/Controller.py#L56), so the input text and options can be reset there.

**Comment by ACast1** [comment]
ENTRY BOXES will now clear when frame is presented

**Comment by zacryol** [comment]
> ENTRY BOXES will now clear when the AddEmployee frame is presented

@ACast1 if you're committing a fix, link the PR so the issue gets closed
also, make more PRs, don't just push every commit to main

**Comment by zacryol** [comment]
Fixed by commit 37909241c4124da61682b8c7185501dbe5ed7a65
