### ISSUE TITLE
No option is provided to add/set passwords

### ISSUE THREAD

**Issue by zacryol** [skippycrow/T3_CS2450_001#59]
The `auth` library has the functionality to do so, but the user is not given the chance to.

**Comment by ACast1** [comment]
Employees can now edit their own passwords
Passwords can now be added to new employees

It works great for me, close if you agree

![IMG1](https://user-images.githubusercontent.com/91992975/145493817-887a8b3c-e508-4b10-9c76-3409a7639c27.PNG)
![IMG2](https://user-images.githubusercontent.com/91992975/145493849-f2c29ae6-4bcf-4d13-91ef-258fcff3dc46.PNG)
![IMG3](https://user-images.githubusercontent.com/91992975/145493867-b5a12be3-f466-4b3b-871a-b2d83ec521ef.PNG)

**Comment by zacryol** [comment]
> It works great for me, close if you agree

@ACast1 if you want someone to review your work, make a Pull Request with the issue linked; don't just push everything to main and comment on the issue with something like "it probably works now"

**Comment by zacryol** [comment]
And it actually doesn't work at all.

the csv does not change, and on top of that, pressing Submit broke the entire program, making even the cancel button throw an error and not do what it should

**Comment by ACast1** [comment]
> > It works great for me, close if you agree
> 
> @ACast1 if you want someone to review your work, make a Pull Request with the issue linked; don't just push everything to main and comment on the issue with something like "it probably works now"

Your quote is way off base from what I actually said XD but close enough if not being a good sport is your goal

**Comment by zacryol** [comment]
I said "something like"

**Comment by ACast1** [comment]
Why say that when github quotes me for you already??

**Comment by zacryol** [comment]
Because there are multiple cases of saying "something like" that when commenting on an issue after pushing the changes directly into main.

**Comment by zacryol** [comment]
Anyway, just a reminder that once this does get working, don't commit any of the changes made to `passwords.csv` unless 1) there is a reason to, and 2) you also change `passwords_real.csv`

**Comment by ACast1** [comment]
This is fixed with https://github.com/skippycrow/T3_CS2450_001/pull/62 After an employee password is updated, the new password still works even after the app is restarted. Admins can now add a password for new employees in the AddEmployee frame.
