### ISSUE TITLE
Add employee permission issue

### ISSUE THREAD

**Issue by skippycrow** [skippycrow/T3_CS2450_001#66]
When you add a new employee there are problems with the information that is being shown 

- Pay amounts aren't shown
- Pay method isn't shown

Existing:
Info:
![image](https://user-images.githubusercontent.com/70984355/145904172-958d86e0-3911-487e-8e36-13dc4f30838b.png)
Shown:
![image](https://user-images.githubusercontent.com/70984355/145904192-24fcebea-b17e-4e3c-9ab2-fca92929e5d0.png)

New employee:
Info:
![image](https://user-images.githubusercontent.com/70984355/145904101-612a7cc4-b994-4973-ba75-2b4a55267f23.png)
shown:
![image](https://user-images.githubusercontent.com/70984355/145904122-60d03007-93fb-4ba7-bb61-89233f24d3ac.png)

**Comment by ACast1** [comment]
It looks like you are using EditEmployee frame to add a new employee instead of AddEmployee frame. Can you confirm this is the case?

**Comment by ACast1** [comment]
Also does this issue occur when all of the entries are filled in? If not, then we can just show an error box telling the user to fill in all entry boxes before adding the new employee

**Comment by skippycrow** [comment]
I was using edit employee to view the data that should have been shown

Same result with all data added

**Comment by skippycrow** [comment]
And yes I did use add employee to create a new one

**Comment by ACast1** [comment]
I figured it out, it was an issue with the new changes made by another person who edited the employee profile. I will be fixed in an upcoming commit to this pull request

**Comment by ACast1** [comment]
The pull request is merged and the issue is fixed for me. Close if you are no longer seeing this issue as well.

**Comment by skippycrow** [comment]
Looks good thanks
